# Generated by Django 3.0 on 2021-02-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
