# Generated by Django 3.0 on 2021-02-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bathroom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='photoUrl',
            field=models.CharField(max_length=100),
        ),
    ]
