# Generated by Django 3.0 on 2021-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210218_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='photoUrl',
            field=models.CharField(max_length=500),
        ),
    ]
