# Generated by Django 3.0 on 2021-02-22 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210219_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bathroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
